name: Main workflow

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
    GITHUB_TOKEN: ${{ secrets.NADEE_GITHUB_TOKEN_FRONTEND }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - id: create-release
        uses: rymndhng/release-on-push-action@master
        with:
        bump_version_scheme: patch
      - name: Build the Docker image
        run: docker build
