name: Main workflow

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.NADEE_GITHUB_TOKEN_FRONTEND }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - id: create-release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch

      - name: Build the Docker image
        run: docker build -t ${{ vars.CONTAINER_IMAGE_REGISTRY }}/${{ vars.CONTAINER_IMAGE_GROUP }}/nr-frontend:latest -t ${{ vars.CONTAINER_IMAGE_REGISTRY }}/${{ vars.CONTAINER_IMAGE_GROUP }}/nr-frontend:${{ steps.create-release.outputs.version }} .

      - name: List Docker images
        run: docker images

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Release to ecr
        run: |
          echo "Pushing image to ECR..."
          docker push ${{ vars.CONTAINER_IMAGE_REGISTRY }}/${{ vars.CONTAINER_IMAGE_GROUP }}/nr-frontend --all-tags
